apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensoft-frontend.fullname" . }}
  labels:
    {{- include "opensoft-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000    # Changes here
      targetPort: {{ .Values.service.port }}  # Changes here
      protocol: TCP
      name: http
  selector:
    {{- include "opensoft-frontend.selectorLabels" . | nindent 4 }}
